from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("maxin-cn/Latte-1")

plain_prompts = {
    "Soldier" : "A weary soldier, clad in a dusty, camouflage uniform, stands solemnly in front of the camera, his eyes reflecting a deep sadness and resignation. His face, marked by the grime of battle and the weight of impending conflict, conveys a poignant awareness that the war is imminent. The background is a blur of military activity, hinting at the chaos about to unfold. His posture is rigid yet somehow defeated, as he clutches his helmet in one hand, a symbol of the protection and burden he carries. The somber lighting casts shadows over his features, emphasizing the heavy toll of his duty and the somber realization that his time to face the horrors of war has arrived.",
    "Ball" : "A small, brightly colored rubber ball bounces rhythmically in slow motion against a wooden floor in a sunlit room. Each time the ball hits the floor, it flattens slightly before springing back into its round shape, reaching different heights with each bounce. The camera is set close to the floor, capturing the textures of the wood grain and the way sunlight highlights the ball’s surface. As it bounces, shadows shift dynamically around it, creating a sense of depth and movement.",
    "Car" : "A sleek, black sports car glides effortlessly through a vibrant cityscape at dusk, its polished surface reflecting the neon lights and towering skyscrapers. The scene transitions to a close-up of the car's grille, highlighting its intricate design and glowing headlights. Next, the camera pans to the driver, a confident man in a stylish leather jacket, his hands gripping the steering wheel with ease. The car accelerates smoothly, leaving a trail of soft, glowing taillights against the backdrop of a starlit night, capturing the essence of luxury and speed.",
    "Purse" : "A sleek, black leather purse rests elegantly on a polished wooden table, its surface reflecting a soft, ambient light. The purse features a delicate gold chain strap and a minimalist, rectangular clasp adorned with a subtle, sparkling gem. As the camera zooms in, the texture of the leather becomes apparent, showcasing its fine grain and supple feel. The background gradually shifts to reveal a luxurious, dimly lit room with velvet curtains and a crystal chandelier, enhancing the purse's aura of sophistication and style. The final shot captures the purse from above, highlighting its compact yet spacious design, perfect for an evening of elegance.",
    "TV" : "A sleek, modern living room comes to life as the central focus shifts to a state-of-the-art, ultra-thin television mounted on a pristine white wall. The TV screen flickers to life, displaying a vibrant, high-definition scene of a bustling cityscape at dusk, with neon lights reflecting off skyscraper windows. Surrounding the TV, the room is adorned with contemporary furniture: a plush gray sofa, a glass coffee table, and minimalist decor. Soft, ambient lighting casts a warm glow, highlighting the contrast between the dynamic on-screen imagery and the serene, inviting atmosphere of the room. The scene captures the perfect blend of technology and comfort, inviting viewers to immerse themselves in the ultimate home entertainment experience.",
    "Sofa" : "A plush, vintage sofa with intricate wooden carvings and deep, velvety red upholstery stands prominently in a cozy, dimly lit living room. The sofa's rich texture contrasts with the warm, golden glow of a nearby floor lamp, casting soft shadows on the walls adorned with eclectic art pieces. A stack of well-read books rests on one arm, while a hand-knitted throw drapes over the back, adding a homely touch. The scene is further enhanced by a small, antique wooden table beside the sofa, holding a steaming cup of tea and a vintage clock ticking gently, creating an inviting atmosphere of comfort and nostalgia.",
    "Bike" : "A sleek, yellow mountain bike stands poised on a rugged, forested trail, its shiny frame reflecting the dappled sunlight filtering through the dense canopy. The scene transitions to a close-up of the bike's intricate gear system, showcasing the precision engineering. Next, a pair of hands in padded gloves grips the handlebars, preparing for a journey. The bike then moves into action, navigating over gnarled roots and rocky terrain, the tires kicking up a spray of dirt. Finally, the bike comes to a rest on a hilltop, overlooking a breathtaking panoramic view of the lush, green valley below, symbolizing the freedom and adventure of cycling.",
    "Horse" : "A majestic black stallion gallops through a sun-drenched meadow, its mane flowing like a dark wave, muscles rippling beneath its sleek coat. The scene shifts to a close-up of the horse's intense, intelligent eyes, reflecting the vibrant green of the surrounding grass. As the stallion rears up, its powerful legs silhouetted against the bright sky, a sense of freedom and strength emanates. The background transitions to a panoramic view of rolling hills and a distant forest, emphasizing the horse's solitary grandeur. Finally, the stallion slows to a gentle trot, its breath visible in the cool morning air, embodying the essence of wild elegance.",
    "Cow" : "A majestic cow stands gracefully in a lush, green meadow, its sleek black coat shimmering under the golden rays of the setting sun. The cow's gentle eyes reflect a sense of serenity, as it gazes peacefully at the horizon. Around it, wildflowers sway gently in the breeze, adding vibrant splashes of color to the scene. The cow's long, elegant lashes catch the light, highlighting its calm and noble presence. In the background, a distant oak tree provides a picturesque silhouette, completing this tranquil snapshot of rural beauty.",
    "Thunder" : "The scene opens with a dark, turbulent sky, heavy with storm clouds. Suddenly, a jagged bolt of lightning pierces through, illuminating the landscape for a brief moment in a blinding flash of white and blue. The rumble of thunder follows, echoing deeply, shaking the ground and resonating with an intense, raw energy. Rain begins to fall in heavy, visible drops, splashing against the ground, while the dim light flickers, casting eerie shadows against the backdrop of a windswept, stormy sky.",
    "Dancer" : "A ballet dancer performs an elegant pirouette on a stage with dim lighting, with a single spotlight illuminating her. She spins gracefully, extending one leg and raising her arms, creating beautiful, flowing movements with her dress billowing around her. The camera slowly pans around her, capturing her graceful expression and focused gaze. The background fades into darkness, putting full focus on her form and movements as she completes the pirouette, transitioning into a smooth arabesque pose, with the spotlight creating a dramatic silhouette effect.",
    "Skier" : "A skier descends a snowy mountain slope at high speed, kicking up powder with each turn. The camera follows closely from behind, capturing the rush of snow and the bright sunlight reflecting off the white landscape. As the skier carves through the snow, you can see the details of their ski gear, the stripes on their helmet, and the motion of their poles slicing through the air. Trees in the background are blurred, emphasizing the speed and intensity of the descent, while the skier performs a quick jump over a small ridge, landing smoothly and continuing down the mountain.",
    "Butterfly" : "A delicate butterfly with iridescent blue and purple wings flutters gracefully above a vibrant meadow, its wings shimmering in the golden sunlight. The scene transitions to a close-up of the butterfly's intricate wing patterns, revealing tiny scales that catch the light. Next, the butterfly lands gently on a bright pink flower, its proboscis extending to sip nectar. The background features a lush green landscape with wildflowers in full bloom, creating a serene and picturesque setting. The butterfly then takes flight again, soaring through the air with effortless elegance, against a backdrop of a clear blue sky dotted with fluffy white clouds.",
    "Mouse" : "A tiny, agile mouse with soft, brown fur and bright, curious eyes scurries through a lush, green forest. It pauses to nibble on a sunlit seed, its whiskers twitching inquisitively. The mouse then darts across a fallen log, its delicate paws barely making a sound on the mossy surface. As it explores, the mouse encounters a vibrant butterfly, causing it to momentarily freeze in awe. The scene shifts to the mouse burrowing into a cozy, leaf-lined nest, its safe haven amidst the towering trees and dappled sunlight.",
    "Crocodile" : "A massive crocodile basks on a riverbank, its scaly, olive-green skin glistening under the tropical sun. Its powerful jaws are slightly agape, revealing rows of sharp, white teeth. The creature's eyes, small but piercing, survey the surroundings with a blend of lethargy and alertness. The river flows gently beside it, reflecting the lush greenery of the jungle canopy above. As the scene shifts, the crocodile slides into the water with a graceful, yet menacing ease, creating ripples that disturb the serene surface, all while maintaining its regal and formidable presence in the heart of the wild.",
    "Farmer" : "A rugged farmer, clad in a weathered denim jacket, dusty overalls, and a wide-brimmed straw hat, stands amidst a golden wheat field at sunset. His calloused hands gently cradle a freshly harvested ear of corn, his face etched with lines of wisdom and resilience. The warm, amber glow of the setting sun bathes the scene, casting long shadows and highlighting the rich, earthy tones of the soil. As he looks out over his sprawling farm, a sense of pride and connection to the land emanates from his weathered features, embodying the timeless spirit of agriculture.",
    "Pilot" : "A seasoned pilot, clad in a sleek black flight suit with a white stripe down the leg, stands confidently in a vast, dimly lit hangar. His aviator sunglasses reflect the soft glow of overhead lights, and his hands rest casually on his hips. The scene shifts to show him striding purposefully towards a state-of-the-art fighter jet, its metallic surface gleaming under the hangar's lights. As he approaches, he reaches up to adjust his pilot's cap, revealing a hint of a determined smile. The background features rows of advanced aircraft and bustling ground crew, emphasizing the high-stakes atmosphere of a military airbase. The pilot's posture exudes authority and readiness, capturing the essence of a skilled aviator preparing for a critical mission.",
    "TaxiDriver" : "A seasoned taxi driver, sporting a classic black cap and a navy blue jacket, navigates the bustling city streets with a focused yet weary expression. The interior of his vintage yellow cab is filled with small trinkets and a worn-out map, reflecting years of service. As he drives, the cityscape whirls past, showcasing neon signs and towering skyscrapers. A close-up reveals his weathered hands gripping the steering wheel, while his eyes briefly meet the rearview mirror, hinting at countless stories shared with passengers. The scene transitions to him pausing at a red light, glancing at a photo of his family taped to the dashboard, a silent testament to his dedication and the life he supports behind the wheel.",
    "Tiger": "A magnificent tiger with a vibrant orange coat and bold black stripes prowls silently through a dense jungle. Its muscular body moves fluidly, each step purposeful and deliberate. The camera focuses on its piercing amber eyes, which radiate a mix of intelligence and untamed power. The tiger pauses near a sunlit clearing, its fur glowing against the backdrop of lush green foliage. A distant roar echoes, blending with the rustle of leaves, emphasizing the tiger's dominance in this wild and verdant domain.",
    "RoadFullofCars": "A bustling urban highway at rush hour, packed with cars of various shapes, sizes, and colors, stretches into the horizon under a cloudy sky. The sound of honking horns and the hum of engines fills the air as vehicles inch forward in a seemingly endless line. The camera pans to a sleek, black sedan weaving skillfully through the traffic, contrasting sharply with an old, rusted pickup nearby. The scene transitions to an aerial view, revealing a labyrinth of intersecting roads and overpasses, capturing the chaos and energy of a city on the move.",
    "River": "A tranquil river meanders through a picturesque valley, its clear, shimmering waters reflecting the vibrant blue sky above. The camera zooms in on the gentle ripples created by a family of ducks paddling along the surface. On the riverbank, tall reeds sway in the breeze, and a lone fisherman sits patiently, his silhouette framed by the golden hues of a setting sun. The scene transitions to a close-up of the water, revealing small fish darting beneath the surface and the intricate patterns of light dancing on the riverbed.",
    "Shore": "A serene shoreline stretches endlessly, where the golden sands meet the crystal-clear waters of the ocean. Waves gently lap against the shore, creating a soothing rhythm as tiny crabs scuttle across the sand. The horizon is painted with hues of orange and pink as the sun begins to set, casting a warm glow over the scene. A lone seagull soars above, its shadow gliding across the rippling water. The camera lingers on a piece of driftwood, weathered and smooth, lying half-buried in the sand, a testament to the timeless dance between land and sea.",
    "Tractor": "A rugged, green tractor sits amidst a sprawling field of golden wheat, its massive wheels caked with dried mud. The sun casts a warm, amber glow, highlighting the faded paint and sturdy frame of the machine. A farmer, clad in a flannel shirt and straw hat, climbs into the driver's seat, his figure silhouetted against the wide expanse of the open sky. As the tractor roars to life, it begins to plow through the field, leaving neat, parallel lines in its wake, embodying the spirit of hard work and harvest.",
    "Airplane": "A gleaming commercial airplane taxis on a sunlit runway, its massive engines emitting a low, steady hum. The camera pans across its sleek, white fuselage adorned with the vibrant logo of an international airline. As the plane accelerates, it lifts gracefully into the air, wings tilting slightly as it ascends into the azure sky. The scene transitions to an interior view, where passengers settle into their seats, gazing out of oval windows at the shrinking cityscape below. The final shot captures the airplane soaring above a sea of fluffy clouds, a symbol of innovation and connection.",
    "Rocket": "A towering rocket, clad in gleaming white and black panels, stands poised on its launchpad against a backdrop of a fiery orange sunset. Plumes of smoke and steam billow from its base as countdown numbers flash on a nearby screen. The camera zooms in on the rocket's powerful engines, which ignite with a thunderous roar, propelling it skyward in a blaze of light and energy. As it ascends, the view shifts to a close-up of its nose cone piercing through the atmosphere, leaving a trail of white contrails against the vast, darkening sky. The final scene reveals the Earth below, a beautiful blue marble, as the rocket continues its journey into space.",
    "Chef": "A masterful chef in a crisp white jacket and tall, starched hat stands confidently in a bustling, high-end restaurant kitchen. His hands move with practiced precision as he chops vibrant vegetables on a wooden cutting board, the rhythmic sound of the knife blending with the background hum of the kitchen. A sizzling pan emits a cloud of fragrant steam as he expertly flips a piece of golden-brown fish. The chef pauses to sprinkle a pinch of herbs over the dish, his face reflecting both concentration and passion. The final scene shows the plated masterpiece—a harmonious blend of colors and textures—being served to a delighted guest.",
    "Doctor": "A compassionate doctor, clad in a spotless white coat and a stethoscope draped around her neck, stands in a brightly lit hospital room. Her warm smile reassures a young patient seated on the examination table, whose small hand is wrapped in hers. The room is filled with medical instruments, neatly organized on counters, and a monitor displaying steady vital signs. The scene transitions to the doctor consulting with colleagues, her expression thoughtful as they review a complex case on a tablet. The final shot captures her stepping out of the hospital, her determined gaze hinting at a day well-spent saving lives.",
}

for k, prompt in plain_prompts:
    image = pipe(prompt).images[0]
    image.save(f"results_LattE/{k}_Fake.png")

